apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-lower-upper-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-lower-upper
  template:
    metadata:
      labels:
        app: java-lower-upper
    spec:
      containers:
        - name: lower-upper
          image: 192.168.1.21:8083/docker-hosted/lowerupper:latest
          ports:
            - containerPort: 8083
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: java-lower-upper
spec:
  selector:
    app: java-lower-upper
  type: LoadBalancer  
  ports:
    - protocol: TCP
      targetPort: 8083
      port: 8083
      nodePort: 30000
